import assert from 'node:assert/strict';
import test from 'node:test';
import { ApiClientError, createApiClient } from '../src/api/client';
function response(payload: unknown, status = 200) { return new Response(JSON.stringify(payload), { status, headers: { 'Content-Type': 'application/json' } }); }
test('uses configured base URL and snake_case chat contract', async () => { let called = ''; let init: RequestInit | undefined; const api = createApiClient({ api_base_url: 'http://192.168.1.2:8000/api/', fetch_impl: async (url, request) => { called = String(url); init = request; return response({ assistant_response: '已记录', intent: 'record_event', extracted_events: [] }); } }); const result = await api.postChat({ user_id: 10001, conversation_id: 'conv_1', user_input: '今天学习数学' }); assert.equal(result.assistant_response, '已记录'); assert.equal(called, 'http://192.168.1.2:8000/api/v1/chat'); assert.deepEqual(JSON.parse(String(init?.body)), { user_id: 10001, conversation_id: 'conv_1', user_input: '今天学习数学' }); });
test('builds events, report and poster URLs', async () => { const calls: string[] = []; const api = createApiClient({ api_base_url: 'https://example.test', fetch_impl: async (url) => { calls.push(String(url)); return response({ items: [], count: 0 }); } }); await api.getLifeEvents(10001, 7); await api.listWeeklyReports(10001, 3); assert.equal(api.getWeeklyPosterUri(4), 'https://example.test/api/v1/weekly-reports/4/poster'); assert.deepEqual(calls, ['https://example.test/api/v1/life-events?user_id=10001&days=7', 'https://example.test/api/v1/weekly-reports?user_id=10001&limit=3']); });
test('converts non-2xx payload to safe ApiClientError', async () => { const api = createApiClient({ api_base_url: 'https://example.test', fetch_impl: async () => response({ success: false, error_code: 'TRANSCRIPTION_UNAVAILABLE', message: '语音服务暂时不可用' }, 503) }); await assert.rejects(() => api.getLifeEvents(10001), (error: unknown) => error instanceof ApiClientError && error.status === 503 && error.error_code === 'TRANSCRIPTION_UNAVAILABLE' && error.message === '语音服务暂时不可用'); });
test('posts multipart speech fields and never auto-sends transcription', async () => { let body: BodyInit | null | undefined; const api = createApiClient({ api_base_url: 'https://example.test', fetch_impl: async (_url, init) => { body = init?.body; return response({ text: '转写文字', language: 'zh-CN', duration_ms: 1000 }); } }); const result = await api.transcribeAudio('file:///recording.m4a', 10001); assert.equal(result.text, '转写文字'); assert.ok(body instanceof FormData); assert.equal((body as FormData).get('user_id'), '10001'); assert.equal((body as FormData).get('language'), 'zh-CN'); });
test('reports missing API configuration instead of using localhost', async () => { const api = createApiClient({ api_base_url: '' }); await assert.rejects(() => api.getLifeEvents(10001), (error: unknown) => error instanceof ApiClientError && error.status === 0 && error.message.includes('EXPO_PUBLIC_API_BASE_URL')); });
