import { MaterialCommunityIcons } from '@expo/vector-icons';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { api_client, type WeeklyReportRecord } from '../api';
import { light_colors, spacing } from '../theme';
export default function WeeklyPosterCard({ report, on_press }: { report: WeeklyReportRecord; on_press: () => void }) {
  const summary = report.report_data.overview?.summary ?? report.report_data.summary ?? '这一周的生活，值得被好好看见。';
  return <Pressable accessibilityRole="button" accessibilityLabel="查看周报详情" onPress={on_press} style={styles.card}><View style={styles.poster}><Image source={{ uri: api_client.getWeeklyPosterUri(report.report_id) }} style={styles.image} resizeMode="cover" /><View style={styles.poster_fallback}><MaterialCommunityIcons color={light_colors.ink} name="chart-box-outline" size={30} /><Text style={styles.fallback_text}>WEEKLY</Text></View></View><View style={styles.copy}><Text style={styles.kicker}>LIFEAGENT WEEKLY</Text><Text style={styles.title}>{report.report_data.overview?.title ?? '本周生活周报'}</Text><Text numberOfLines={2} style={styles.summary}>{summary}</Text><Text style={styles.link}>查看详情  ›</Text></View></Pressable>;
}
const styles = StyleSheet.create({ card: { flexDirection: 'row', gap: spacing.md, marginBottom: spacing.md, padding: spacing.md, borderRadius: 18, backgroundColor: light_colors.paper }, poster: { width: 92, height: 116, borderRadius: 12, overflow: 'hidden', backgroundColor: light_colors.blue, alignItems: 'center', justifyContent: 'center' }, image: { ...StyleSheet.absoluteFillObject }, poster_fallback: { alignItems: 'center', justifyContent: 'center', gap: 3 }, fallback_text: { color: light_colors.ink, fontSize: 9, fontWeight: '800' }, copy: { flex: 1, justifyContent: 'center', gap: 5 }, kicker: { color: light_colors.muted, fontSize: 10, letterSpacing: 1 }, title: { color: light_colors.ink, fontWeight: '800', fontSize: 16 }, summary: { color: light_colors.muted, fontSize: 12, lineHeight: 18 }, link: { color: light_colors.ink, fontSize: 12, fontWeight: '700', marginTop: 2 } });
