import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api_client, type WeeklyReportRecord } from '../api';
import WeeklyPosterCard from '../components/WeeklyPosterCard';
import { useWorkspace } from '../state/WorkspaceContext';
import { light_colors, spacing } from '../theme';

export default function HomeScreen() {
  const navigation = useNavigation<any>();
  const { data, colors, update } = useWorkspace();
  const [reports, setReports] = useState<WeeklyReportRecord[]>([]);
  const [report_loading, setReportLoading] = useState(true);
  const [report_error, setReportError] = useState('');
  const [search, setSearch] = useState('');
  useEffect(() => { let active = true; setReportLoading(true); api_client.listWeeklyReports(10001, 3).then((result) => { if (active) setReports(result.items); }).catch(() => { if (active) setReportError('周报暂时无法加载'); }).finally(() => { if (active) setReportLoading(false); }); return () => { active = false; }; }, []);
  const visible_tasks = useMemo(() => data.tasks.filter((task) => task.task_name.toLowerCase().includes(search.trim().toLowerCase())), [data.tasks, search]);
  const completed = data.tasks.filter((task) => task.completed).length;
  function toggle_task(task_id: string) { update({ ...data, tasks: data.tasks.map((task) => task.task_id === task_id ? { ...task, completed: !task.completed } : task) }); }
  function open_report(report: WeeklyReportRecord) { navigation.getParent()?.navigate('周报详情', { report }); }
  return <ScrollView contentContainerStyle={[styles.content, { backgroundColor: colors.canvas }]}>
    <View style={[styles.hero, { backgroundColor: colors.ink }]}><Text style={[styles.eyebrow_light, { color: colors.muted }]}>星期一，8月24日</Text><Text style={[styles.greeting, { color: colors.paper }]}>嗨，Marimar!</Text><Text style={[styles.hero_copy, { color: colors.muted }]}>开启你今天的学习之旅</Text><View style={styles.search}><MaterialCommunityIcons color={colors.muted} name="magnify" size={21} /><TextInput value={search} onChangeText={setSearch} placeholder="搜索任务或项目" placeholderTextColor={colors.muted} style={[styles.search_input, { color: colors.ink }]} /><Pressable accessibilityRole="button" accessibilityLabel="打开定制" onPress={() => navigation.navigate('定制')} style={[styles.search_action, { backgroundColor: colors.ink }]}><MaterialCommunityIcons color={colors.paper} name="tune-variant" size={18} /></Pressable></View></View>
    <View style={styles.section_heading}><Text style={[styles.section_title, { color: colors.ink }]}>项目</Text><Pressable onPress={() => navigation.navigate('定制')}><Text style={[styles.edit_link, { color: colors.muted }]}>编辑全部</Text></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.project_scroller}><View style={[styles.project_card, styles.dark_card, { backgroundColor: colors.ink }]}><View style={styles.card_icon}><MaterialCommunityIcons color={colors.ink} name="account-heart-outline" size={19} /></View><View style={styles.arrow}><MaterialCommunityIcons color={colors.ink} name="arrow-top-right" size={19} /></View><Text style={[styles.project_title, { color: colors.paper }]}>{data.project_name === '事件提醒' ? '今日计划' : data.project_name}</Text><Text style={[styles.project_copy, { color: colors.muted }]}>{data.project_description}</Text><Text style={[styles.project_status, { color: colors.paper }]}>● 进行中 · {data.tasks.length} 个任务</Text></View><View style={[styles.project_card, styles.blue_card, { backgroundColor: colors.blue }]}><View style={styles.card_icon}><MaterialCommunityIcons color={colors.ink} name="moon-waning-crescent" size={19} /></View><Text style={[styles.project_title, { color: colors.ink }]}>睡眠时间</Text><Text style={[styles.project_copy, { color: colors.muted }]}>记录总结这一周的作息</Text><Text style={[styles.project_status, { color: colors.ink }]}>● 草稿 · 2 个任务</Text></View></ScrollView>
    <View style={styles.section_heading}><Text style={[styles.section_title, { color: colors.ink }]}>任务</Text><Text style={[styles.eyebrow, { color: colors.muted }]}>{completed}/{data.tasks.length} 已完成</Text></View>
    <View style={styles.task_list}>{visible_tasks.map((task) => <Pressable accessibilityRole="button" accessibilityLabel={`${task.task_name}${task.completed ? '，已完成' : ''}`} key={task.task_id} onPress={() => toggle_task(task.task_id)} style={[styles.task_row, { backgroundColor: colors.paper }]}><View style={[styles.checkbox, task.completed && { backgroundColor: colors.ink, borderColor: colors.ink }]}>{task.completed && <MaterialCommunityIcons color={colors.paper} name="check" size={18} />}</View><Text style={[styles.task_text, { color: task.completed ? colors.muted : colors.ink }, task.completed && styles.completed_text]}>{task.task_name}</Text><MaterialCommunityIcons color={colors.ink} name="dots-horizontal" size={20} /></Pressable>)}</View>
    <Pressable accessibilityRole="button" onPress={() => navigation.navigate('聊天')} style={[styles.chat_cta, { backgroundColor: colors.ink }]}><Text style={[styles.chat_cta_text, { color: colors.paper }]}>和 LifeAgent 聊聊今天</Text><MaterialCommunityIcons color={colors.paper} name="arrow-right" size={21} /></Pressable>
    <View style={styles.section_heading}><Text style={[styles.section_title, { color: colors.ink }]}>最近周报</Text><Pressable onPress={() => api_client.listWeeklyReports(10001, 10).then((result) => setReports(result.items))}><Text style={[styles.edit_link, { color: colors.muted }]}>刷新</Text></Pressable></View>
    {report_loading && <View style={styles.state}><ActivityIndicator color={colors.ink} /><Text style={[styles.muted, { color: colors.muted }]}>正在加载周报...</Text></View>}
    {!report_loading && report_error !== '' && <View style={styles.state}><Text style={[styles.muted, { color: colors.muted }]}>{report_error}</Text></View>}
    {!report_loading && !report_error && reports.length === 0 && <View style={styles.state}><Text style={[styles.muted, { color: colors.muted }]}>暂无周报，先去记录今天的生活。</Text></View>}
    {reports.map((report) => <WeeklyPosterCard key={report.report_id} report={report} on_press={() => open_report(report)} />)}
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { flexGrow: 1, paddingBottom: 30 }, hero: { padding: 24, paddingTop: 30, borderBottomLeftRadius: 30, borderBottomRightRadius: 30 }, eyebrow_light: { fontSize: 11, letterSpacing: 1, marginBottom: 11 }, greeting: { fontSize: 28, lineHeight: 34, fontWeight: '700', marginBottom: 4 }, hero_copy: { fontSize: 14, marginBottom: 23 }, search: { height: 50, paddingLeft: 14, paddingRight: 7, borderRadius: 15, backgroundColor: light_colors.paper, flexDirection: 'row', alignItems: 'center', gap: 8 }, search_input: { flex: 1, minWidth: 0, fontSize: 13 }, search_action: { width: 36, height: 36, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, section_heading: { paddingHorizontal: 24, paddingTop: 22, paddingBottom: 13, flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between' }, section_title: { fontSize: 21, fontWeight: '700' }, edit_link: { fontSize: 12 }, eyebrow: { fontSize: 12 }, project_scroller: { paddingHorizontal: 24, paddingBottom: 7, gap: 14 }, project_card: { width: 222, minHeight: 222, padding: 20, borderRadius: 27, position: 'relative' }, dark_card: {}, blue_card: {}, card_icon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' }, arrow: { position: 'absolute', top: 18, right: 18, width: 36, height: 36, borderRadius: 18, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' }, project_title: { marginTop: 48, marginBottom: 8, fontSize: 22, fontWeight: '700' }, project_copy: { minHeight: 39, fontSize: 12, lineHeight: 19 }, project_status: { marginTop: 20, fontSize: 11, fontWeight: '700' }, task_list: { gap: 10, paddingHorizontal: 24 }, task_row: { minHeight: 58, padding: 14, borderRadius: 17, flexDirection: 'row', alignItems: 'center', gap: 12 }, checkbox: { width: 28, height: 28, borderWidth: 2, borderColor: '#D8D8D5', borderRadius: 9, alignItems: 'center', justifyContent: 'center' }, task_text: { flex: 1, fontSize: 14 }, completed_text: { textDecorationLine: 'line-through' }, chat_cta: { marginHorizontal: 24, marginTop: 20, minHeight: 54, paddingHorizontal: 18, borderRadius: 17, alignItems: 'center', justifyContent: 'space-between', flexDirection: 'row' }, chat_cta_text: { fontSize: 13, fontWeight: '700' }, state: { marginHorizontal: 24, padding: 22, borderRadius: 18, alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: light_colors.paper }, muted: { fontSize: 13, lineHeight: 20 } });
